
-- Criar usuários diretamente na tabela auth.users com email confirmado
INSERT INTO auth.users (
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  phone_confirmed_at,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmation_sent_at,
  recovery_sent_at,
  email_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  phone,
  instance_id
) VALUES
-- w.williamvidal@gmail.com
(
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'w.williamvidal@gmail.com',
  crypt('Teste12345@', gen_salt('bf')),
  now(),
  null,
  '',
  '',
  '',
  '',
  '',
  '',
  null,
  now(),
  null,
  null,
  0,
  null,
  '',
  null,
  false,
  null,
  false,
  '{"provider":"email","providers":["email"]}',
  '{"nome":"William Vidal","tipo_plano":"pro"}',
  now(),
  now(),
  null,
  '00000000-0000-0000-0000-000000000000'
),
-- lauraferreirapassos@gmail.com
(
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'lauraferreirapassos@gmail.com',
  crypt('Teste12345@', gen_salt('bf')),
  now(),
  null,
  '',
  '',
  '',
  '',
  '',
  '',
  null,
  now(),
  null,
  null,
  0,
  null,
  '',
  null,
  false,
  null,
  false,
  '{"provider":"email","providers":["email"]}',
  '{"nome":"Laura Ferreira Passos","tipo_plano":"pro"}',
  now(),
  now(),
  null,
  '00000000-0000-0000-0000-000000000000'
),
-- sophiapaula1@gmail.com
(
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'sophiapaula1@gmail.com',
  crypt('Teste12345@', gen_salt('bf')),
  now(),
  null,
  '',
  '',
  '',
  '',
  '',
  '',
  null,
  now(),
  null,
  null,
  0,
  null,
  '',
  null,
  false,
  null,
  false,
  '{"provider":"email","providers":["email"]}',
  '{"nome":"Sophia Paula","tipo_plano":"pro"}',
  now(),
  now(),
  null,
  '00000000-0000-0000-0000-000000000000'
),
-- gabriellevergani@hotmail.com
(
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'gabriellevergani@hotmail.com',
  crypt('Teste12345@', gen_salt('bf')),
  now(),
  null,
  '',
  '',
  '',
  '',
  '',
  '',
  null,
  now(),
  null,
  null,
  0,
  null,
  '',
  null,
  false,
  null,
  false,
  '{"provider":"email","providers":["email"]}',
  '{"nome":"Gabrielle Vergani","tipo_plano":"pro"}',
  now(),
  now(),
  null,
  '00000000-0000-0000-0000-000000000000'
);

-- Criar identidades para os usuários (removendo a coluna email gerada)
INSERT INTO auth.identities (
  provider_id,
  user_id,
  identity_data,
  provider,
  last_sign_in_at,
  created_at,
  updated_at,
  id
)
SELECT 
  u.id,
  u.id,
  jsonb_build_object(
    'sub', u.id::text,
    'email', u.email,
    'email_verified', true,
    'phone_verified', false
  ),
  'email',
  now(),
  now(),
  now(),
  gen_random_uuid()
FROM auth.users u 
WHERE u.email IN (
  'w.williamvidal@gmail.com',
  'lauraferreirapassos@gmail.com', 
  'sophiapaula1@gmail.com',
  'gabriellevergani@hotmail.com'
)
AND NOT EXISTS (
  SELECT 1 FROM auth.identities i WHERE i.user_id = u.id
);
;
