-- Cria a tabela 'contas_instagram' para armazenar as informações de autenticação
CREATE TABLE public.contas_instagram (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL,
    instagram_user_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Adiciona comentários para explicar o propósito da tabela e de cada coluna
COMMENT ON TABLE public.contas_instagram IS 'Armazena as credenciais (tokens) e IDs de cada conta do Instagram conectada à plataforma.';
COMMENT ON COLUMN public.contas_instagram.id IS 'Identificador único para cada conta conectada.';
COMMENT ON COLUMN public.contas_instagram.usuario_id IS 'ID do usuário na sua plataforma (Lovable), para saber de quem é esta conta.';
COMMENT ON COLUMN public.contas_instagram.access_token IS 'O token de acesso fornecido pela Meta para fazer chamadas à API.';
COMMENT ON COLUMN public.contas_instagram.instagram_user_id IS 'O ID da conta de negócios do Instagram retornado pela API.';

-- Habilita Row Level Security
ALTER TABLE public.contas_instagram ENABLE ROW LEVEL SECURITY;

-- Políticas RLS: usuários podem ver apenas suas próprias contas
CREATE POLICY "Users can view their own instagram accounts"
ON public.contas_instagram
FOR SELECT
USING (auth.uid() = usuario_id);

CREATE POLICY "Users can insert their own instagram accounts"
ON public.contas_instagram
FOR INSERT
WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Users can update their own instagram accounts"
ON public.contas_instagram
FOR UPDATE
USING (auth.uid() = usuario_id);

CREATE POLICY "Users can delete their own instagram accounts"
ON public.contas_instagram
FOR DELETE
USING (auth.uid() = usuario_id);;
